apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    run: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: myapp
  template:
    metadata:
      name: myapp-pod
      labels:
        run: myapp
    spec:
      containers:
      - name: py-fastapi-app
        image: shubhamsaxena2207/py_fastapi_app:latest
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-root-credentials-flask
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-root-credentials-flask
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-conf-flask
              key: name
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: db-conf-flask
              key: host
        volumeMounts:
          - mountPath: /orders
            name: mysql-persistent-storage
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    run: myapp
spec:
  selector:
    run: myapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000